#!/bin/bash
# TribanFT NFTables Setup Script
#
# Creates required NFTables sets for TribanFT blacklist management
#
# Usage: sudo ./setup_nftables.sh
#
# Author: TribanFT Project
# License: GNU GPL v3

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}ERROR: This script must be run as root${NC}"
    echo "Usage: sudo $0"
    exit 1
fi

# Check if nftables is installed
if ! command -v nft &> /dev/null; then
    echo -e "${RED}ERROR: nftables is not installed${NC}"
    echo "Install with: apt-get install nftables (Debian/Ubuntu)"
    echo "              dnf install nftables (Fedora/RHEL)"
    exit 1
fi

echo -e "${GREEN}TribanFT NFTables Setup${NC}"
echo "========================================"

# Create table if it doesn't exist
echo -n "Creating inet filter table..."
if ! nft list table inet filter &> /dev/null; then
    nft add table inet filter
    echo -e " ${GREEN}Created${NC}"
else
    echo -e " ${YELLOW}Already exists${NC}"
fi

# Create port_scanners set
echo -n "Creating port_scanners set..."
if nft list set inet filter port_scanners &> /dev/null; then
    echo -e " ${YELLOW}Already exists${NC}"
else
    nft add set inet filter port_scanners '{ type ipv4_addr; flags dynamic, timeout; timeout 14400m; }'
    echo -e " ${GREEN}Created${NC}"
fi

# Create blacklist_ipv4 set
echo -n "Creating blacklist_ipv4 set..."
if nft list set inet filter blacklist_ipv4 &> /dev/null; then
    echo -e " ${YELLOW}Already exists${NC}"
else
    nft add set inet filter blacklist_ipv4 '{ type ipv4_addr; flags interval; }'
    echo -e " ${GREEN}Created${NC}"
fi

# Create blacklist_ipv6 set
echo -n "Creating blacklist_ipv6 set..."
if nft list set inet filter blacklist_ipv6 &> /dev/null; then
    echo -e " ${YELLOW}Already exists${NC}"
else
    nft add set inet filter blacklist_ipv6 '{ type ipv6_addr; flags interval; }'
    echo -e " ${GREEN}Created${NC}"
fi

# Create input chain if it doesn't exist
echo -n "Creating input chain..."
if ! nft list chain inet filter input &> /dev/null; then
    nft add chain inet filter input '{ type filter hook input priority 0; policy accept; }'
    echo -e " ${GREEN}Created${NC}"
else
    echo -e " ${YELLOW}Already exists${NC}"
fi

# Add drop rules for blacklisted IPs
echo -n "Adding blacklist drop rules..."
# Check if rules already exist
if nft list chain inet filter input 2>/dev/null | grep -q "ip saddr @blacklist_ipv4 drop"; then
    echo -e " ${YELLOW}IPv4 rule already exists${NC}"
else
    nft insert rule inet filter input ip saddr @blacklist_ipv4 drop
    echo -e " ${GREEN}IPv4 rule added${NC}"
fi

if nft list chain inet filter input 2>/dev/null | grep -q "ip6 saddr @blacklist_ipv6 drop"; then
    echo -e " ${YELLOW}IPv6 rule already exists${NC}"
else
    nft insert rule inet filter input ip6 saddr @blacklist_ipv6 drop
    echo -e " ${GREEN}IPv6 rule added${NC}"
fi

# Save configuration (only TribanFT-specific rules)
echo -n "Saving NFTables configuration..."
TRIBANFT_NFT_FILE="/etc/nftables.d/tribanft.nft"

if [ -d /etc/nftables.d ]; then
    # Debian/Ubuntu style - create separate include file
    cat > "$TRIBANFT_NFT_FILE" << 'NFTEOF'
# TribanFT NFTables Configuration
# Auto-generated by setup_nftables.sh
# DO NOT EDIT MANUALLY - changes will be overwritten

# Create sets if they don't exist
add table inet filter
add set inet filter port_scanners { type ipv4_addr; flags dynamic, timeout; timeout 14400m; }
add set inet filter blacklist_ipv4 { type ipv4_addr; flags interval; }
add set inet filter blacklist_ipv6 { type ipv6_addr; flags interval; }

# Create input chain if it doesn't exist
add chain inet filter input { type filter hook input priority 0; policy accept; }

# Add drop rules for blacklisted IPs
insert rule inet filter input ip saddr @blacklist_ipv4 drop
insert rule inet filter input ip6 saddr @blacklist_ipv6 drop
NFTEOF
    echo -e " ${GREEN}Saved to $TRIBANFT_NFT_FILE${NC}"
    echo -e " ${YELLOW}NOTE: Include this file in your main nftables config${NC}"
else
    # No /etc/nftables.d directory - user must persist manually
    echo -e " ${YELLOW}Skipped - no /etc/nftables.d directory${NC}"
    echo -e " ${YELLOW}WARNING: Rules are active but not persistent across reboots${NC}"
    echo -e " ${YELLOW}To persist, save with: nft list ruleset > /etc/nftables.conf${NC}"
fi

# Enable nftables service
echo -n "Enabling nftables service..."
if systemctl is-enabled nftables &> /dev/null; then
    echo -e " ${YELLOW}Already enabled${NC}"
else
    systemctl enable nftables
    echo -e " ${GREEN}Enabled${NC}"
fi

echo ""
echo -e "${GREEN}NFTables setup complete!${NC}"
echo ""
echo "Created sets:"
echo "  - inet filter port_scanners (dynamic, timeout 14400m)"
echo "  - inet filter blacklist_ipv4 (interval)"
echo "  - inet filter blacklist_ipv6 (interval)"
echo ""
echo "Verify with: sudo nft list ruleset"
echo ""
echo "Next steps:"
echo "  1. Configure TribanFT in ~/.local/share/tribanft/config.conf"
echo "  2. Set enable_nftables_update = true in [features] section"
echo "  3. Start TribanFT service: sudo systemctl start tribanft"
